### ISSUE TITLE
Improving Documentation for Obsidian Integration

### ISSUE THREAD

**Issue by Domenic-MZS** [Domenic-MZS/Essential-ARscape#10]
**Describe the Issue**
The current documentation lacks comprehensive guidance on utilizing Obsidian for project-related tasks, including compatibility, formats, and essential scripts needed for seamless integration and collaboration.

**Suggested Improvement**

1. **Compatibility and Requirements:**
   - Clarify Obsidian's compatibility with the project files and markdown formats. Detail the supported versions and potential compatibility issues to anticipate.
   - List the necessary system requirements and dependencies to effectively use Obsidian within the project's environment.

2. **Setup Instructions:**
   - Provide step-by-step instructions on setting up Obsidian to work seamlessly with the project files. Include guidance on installation, configurations, and any required plugins or settings for optimal functionality.
   - Explain any specific folder structures or organizational tips to ensure a smoother workflow between the project and Obsidian.

3. **Markdown Formats and Styling:**
   - Detail preferred markdown formats, styles, and conventions to maintain consistency between Obsidian and the project files. Highlight any differences or recommended practices for smoother editing and readability.
   - Provide guidelines on using Obsidian-specific features (e.g., backlinks, graph view) to enhance navigation and understanding within the project documentation.

4. **Integration with Scripts or Automation:**
   - Outline any scripts, tools, or automation methods that streamline the synchronization or interaction between Obsidian and the project's version control system (if applicable). Include any recommended workflows or best practices.

**Additional Context**
 - [Automated Code Format Validations & Fixes](#8)

**Comment by Domenic-MZS** [comment]
Test & Requirements are needed too! #8

**Comment by Mobinake** [comment]
nice
